# Generated by Django 5.1.2 on 2024-10-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='esgdata',
            name='environmental',
        ),
        migrations.RemoveField(
            model_name='esgdata',
            name='esg_score',
        ),
        migrations.RemoveField(
            model_name='esgdata',
            name='governance',
        ),
        migrations.RemoveField(
            model_name='esgdata',
            name='social',
        ),
        migrations.AddField(
            model_name='esgdata',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='esgdata',
            name='metric_type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esgdata',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='esgdata',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
