# Generated by Django 5.1.2 on 2024-10-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_api', '0002_remove_esgdata_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('esg_score', models.FloatField()),
                ('environmental', models.FloatField()),
                ('social', models.FloatField()),
                ('governance', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ESGData',
        ),
    ]
