# Generated by Django 5.1.2 on 2024-10-17 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_api', '0003_company_delete_esgdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='environmental',
        ),
        migrations.RemoveField(
            model_name='company',
            name='esg_score',
        ),
        migrations.RemoveField(
            model_name='company',
            name='governance',
        ),
        migrations.RemoveField(
            model_name='company',
            name='social',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ESGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental', models.FloatField()),
                ('social', models.FloatField()),
                ('governance', models.FloatField()),
                ('esg_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg_api.company')),
            ],
        ),
    ]
